sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  hwobs:
    access-key-id: OQQ8KNIEPVDM4MVKFHSN
    access-key-secret: 5wjwYKuxSu9sCyVgBsc1S0Cqgl8ncvx7qEYRMnMg
    endpoint: obs.cn-north-4.myhuaweicloud.com
    bucket-name: sky-take-out-2dae