sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 111.119.211.126
    port: 3306
    database: sky_take_out
    username: root
    password: Zhang_0312
  hwobs:
    access-key-id: OQQ8KNIEPVDM4MVKFHSN
    access-key-secret: 5wjwYKuxSu9sCyVgBsc1S0Cqgl8ncvx7qEYRMnMg
    endpoint: obs.cn-north-4.myhuaweicloud.com
    bucket-name: sky-take-out-2dae
  redis:
    host: 111.119.211.126
    port: 6379
    password: 1234
    database: 0